version: '3.8'

services:
  service-pg:
    image: postgres:16.9-alpine
    container_name: library_postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: library_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
