version: '3.8'

services:
  service-pg:
    image: postgres:16.9-alpine
    container_name: library_postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: library_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - net-libray-api

  service-redis:
    image: redis:7.0-alpine
    container_name: library_redis
    ports:
      - '6379:6379'
    volumes:
      - redisdata:/data
    networks:
      - net-libray-api

volumes:
  pgdata:
  redisdata:

networks:
  net-libray-api:
    driver: bridge
